name: Manual
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose Environment:"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
          - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: echo "Deploying the applications.."
    
